# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la ville')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='Commentaire')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date du commentaire')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du pays')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre ou description de l'\xe9v\xe8nement")),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Affiche')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name="D\xe9but de l'\xe9venement")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name="Fin de l'\xe9venement")),
                ('month_is_estimated', models.BooleanField(default=False, verbose_name='Le mois est estim\xe9')),
                ('day_is_estimated', models.BooleanField(default=False, verbose_name='Le jour est estim\xe9')),
            ],
            options={
                'verbose_name': '\xc9v\xe9nement',
                'verbose_name_plural': '\xc9v\xe9nement',
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'interpr\xe8te")),
            ],
            options={
                'verbose_name': 'Interpr\xe8te',
                'verbose_name_plural': 'Interpr\xe8tes',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Titre de l'\u0153uvre interpret\xe9e")),
            ],
            options={
                'verbose_name': '\u0152uvre',
                'verbose_name_plural': '\u0152uvre',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=200, verbose_name='Lieu')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozartweb.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozartweb.Country')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieu',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, max_length=150, verbose_name="Titre de l'article")),
                ('journal_title', models.CharField(blank=True, max_length=150, verbose_name='Titre du journal')),
                ('page', models.CharField(blank=True, max_length=150, verbose_name='Page(s)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('article_file', models.FileField(blank=True, null=True, upload_to='articles', verbose_name='Article en PDF')),
            ],
            options={
                'verbose_name': 'R\xe9f\xe9rence',
                'verbose_name_plural': 'R\xe9f\xe9rences',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome du/de la conf\xe9rencier/\xe8re')),
            ],
            options={
                'verbose_name': 'Conf\xe9rencier/\xe8re',
                'verbose_name_plural': 'Conf\xe9renciers/\xe8res',
            },
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Conf\xe9rence sans titre', max_length=200, verbose_name='Titre de la conf\xe9rence')),
                ('speaker', models.ManyToManyField(blank=True, to='mozartweb.Speaker', verbose_name='Nome du/de la conf\xe9rencier/\xe8re')),
            ],
            options={
                'verbose_name': 'Conf\xe9rence',
                'verbose_name_plural': 'Conf\xe9rences',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, verbose_name="Nature de l'\xe9v\xe9nement")),
            ],
            options={
                'verbose_name': "Nature de l'\xe9v\xe9nement",
                'verbose_name_plural': "Nature de l'\xe9v\xe9nement",
            },
        ),
        migrations.AddField(
            model_name='event',
            name='performer',
            field=models.ManyToManyField(blank=True, to='mozartweb.Performer', verbose_name='Interpr\xe8tes'),
        ),
        migrations.AddField(
            model_name='event',
            name='piece',
            field=models.ManyToManyField(blank=True, to='mozartweb.Piece', verbose_name='\u0152uvres interpret\xe9es'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozartweb.Place', verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='event',
            name='reference',
            field=models.ManyToManyField(blank=True, to='mozartweb.Reference', verbose_name='R\xe9f\xe9rence'),
        ),
        migrations.AddField(
            model_name='event',
            name='relates_to_radio',
            field=models.ManyToManyField(blank=True, to='mozartweb.Event', verbose_name='Radio difusion'),
        ),
        migrations.AddField(
            model_name='event',
            name='speech',
            field=models.ManyToManyField(blank=True, to='mozartweb.Speech', verbose_name='Conf\xe9rence'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozartweb.Type', verbose_name="Nature de l'\xe9v\xe8nement"),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='mozartweb.Event', verbose_name='\xc9v\xe9nement'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
    ]
