# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0002_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='piece',
            field=models.ManyToManyField(to='mozartweb.Piece'),
        ),
    ]
