# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-13 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0003_auto_20170213_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Ville', 'verbose_name_plural': 'Ville'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name': 'Pays', 'verbose_name_plural': 'Pays'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('type',), 'verbose_name': "Nature de l'\xe9v\xe9nement", 'verbose_name_plural': "Nature de l'\xe9v\xe9nement"},
        ),
    ]
