# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-13 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0004_auto_20170213_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('title',), 'verbose_name': '\xc9v\xe9nement', 'verbose_name_plural': '\xc9v\xe9nement'},
        ),
        migrations.AlterModelOptions(
            name='performer',
            options={'ordering': ('last_name',), 'verbose_name': 'Interpr\xe8te', 'verbose_name_plural': 'Interpr\xe8tes'},
        ),
        migrations.AlterModelOptions(
            name='performertype',
            options={'ordering': ('description',), 'verbose_name': "Nature de l'interpr\xe8te", 'verbose_name_plural': "Natures de l'interpr\xe8te"},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ('name',), 'verbose_name': '\u0152uvre', 'verbose_name_plural': '\u0152uvre'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('venue',), 'verbose_name': 'Lieu', 'verbose_name_plural': 'Lieu'},
        ),
        migrations.AlterModelOptions(
            name='radiostation',
            options={'ordering': ('name',), 'verbose_name': 'Station radio', 'verbose_name_plural': 'Station radio'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('article_title',), 'verbose_name': 'R\xe9f\xe9rence', 'verbose_name_plural': 'R\xe9f\xe9rences'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ('last_name',), 'verbose_name': 'Conf\xe9rencier/\xe8re', 'verbose_name_plural': 'Conf\xe9renciers/\xe8res'},
        ),
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ('title',), 'verbose_name': 'Conf\xe9rence', 'verbose_name_plural': 'Conf\xe9rences'},
        ),
    ]
