# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0005_auto_20170213_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom de la ville'),
        ),
    ]
