# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-27 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0007_auto_20170227_1731'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('city', 'country', 'venue')]),
        ),
    ]
