# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-02 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0013_auto_20170301_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bc_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bc_key', to='mozartweb.Broadcasting', verbose_name='BC KEY (ne pas changer!)'),
        ),
    ]
