# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0015_auto_20170610_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pdf_checked',
            field=models.BooleanField(default=False, verbose_name='PDF v\xe9rifi\xe9'),
        ),
    ]
