# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-29 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0018_remove_comment_broadcasting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='month_is_estimated',
            field=models.BooleanField(default=False, verbose_name='Ignorer le mois et le jour'),
        ),
    ]
