# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-31 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mozartweb', '0019_auto_20170829_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Informations compl\xe9mentaires')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'insertion")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('evt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='mozartweb.Event', verbose_name='\xc9v\xe9nement')),
            ],
            options={
                'verbose_name': 'Informations compl\xe9mentaires',
                'verbose_name_plural': 'Informations compl\xe9mentaires',
            },
        ),
        migrations.AddField(
            model_name='broadcasting',
            name='additional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozartweb.AdditionalInfo', verbose_name='Informations compl\xe9mentaires'),
        ),
        migrations.AddField(
            model_name='event',
            name='additional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozartweb.AdditionalInfo', verbose_name='Informations compl\xe9mentaires'),
        ),
    ]
