# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-31 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0020_auto_20170831_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='evt',
        ),
    ]
