# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-31 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mozartweb', '0021_remove_additionalinfo_evt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_on', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
        ),
        migrations.RenameField(
            model_name='additionalinfo',
            old_name='created_date',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='additionalinfolog',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozartweb.AdditionalInfo', verbose_name='Informations'),
        ),
    ]
