# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-31 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0022_auto_20170831_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcasting',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='event',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='mozartweb.Event', verbose_name='\xc9v\xe9nement'),
        ),
    ]
