# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0023_auto_20170831_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfolog',
            options={'verbose_name': 'Informations compl\xe9mentaires LOG', 'verbose_name_plural': 'Informations compl\xe9mentaires LOG'},
        ),
        migrations.AlterField(
            model_name='additionalinfolog',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='mozartweb.AdditionalInfo', verbose_name='Informations'),
        ),
    ]
