# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-31 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0024_auto_20170831_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfolog',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='mozartweb.AdditionalInfo', verbose_name='Informations'),
        ),
    ]
