# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0028_auto_20170903_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='created_on',
            field=models.DateTimeField(verbose_name="Date d'insertion"),
        ),
    ]
