# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-14 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0031_remove_broadcasting_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du journal')),
            ],
            options={
                'verbose_name': 'Titre du journal',
                'verbose_name_plural': 'Titre du journal',
            },
        ),
        migrations.AlterField(
            model_name='reference',
            name='journal_title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Titre du journal OLD'),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='reference',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mozartweb.Journal', verbose_name='Titre du journal'),
        ),
    ]
