# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-14 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mozartweb', '0032_auto_20170913_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='journal_title',
        ),
    ]
